### ISSUE TITLE
String text in jsx components and git changes

### ISSUE THREAD

**Issue by rffensick** [tcd/dark-plus-syntax#1]
Please fix in stateless components! => 
![default](https://user-images.githubusercontent.com/16798940/38172173-20e544e0-35c9-11e8-9f49-54910c840dda.png)

And color of the files of git changes from the green to orange and vice versa =>
![default](https://user-images.githubusercontent.com/16798940/38172188-43db733e-35c9-11e8-8467-42a4ae75bb02.png)

**Comment by rffensick** [comment]
and keyframes in scss please))) xDD
![image](https://user-images.githubusercontent.com/16798940/38172559-22e84902-35d0-11e8-809e-61bc419965f5.png)

**Comment by dunstontc** [comment]
@rffensick Sorry I haven't gotten back to you sooner. About these issues:
1. I can't seem to recreate the blue color inside of regular tags in a functional component like you've got in the image.  Do you still happen to have that file? Also, what (if any) plugins are you using for JSX highlighting?
2. The color changes reflecting git status aren't part of the plugin. [They're actually a default feature of VSCode.](https://github.com/Microsoft/vscode/wiki/Roadmap#workbench) But you can turn them off by setting:
```json
  // Controls if Git contributes colors and badges to the explorer and the open editors view.
  "git.decorations.enabled": false,
```
3. This should be fixed in v0.0.69 :)

**Comment by rffensick** [comment]
@dunstontc Year, still blue text(((((((. I do not use any plugins for syntax highlighting.

**Comment by def14nt** [comment]
It's nothing to do with the `git` client. @dunstontc Any luck yet?

**Comment by def14nt** [comment]
@rffensick Could you answer some of his questions, too? Trust me, developers need to know this to properly debug.
